active=yes
author=Tafaz
id=DA-phpversionlist
installed=yes
name=DA PHP version list
version=1.0.0
admin_run_as=diradmin
update_url=https://github.com/Tafaz/DA-phpversionlist/blob/main/DA-phpversionlist.tar.gz
version_url=https://github.com/Tafaz/DA-phpversionlist/blob/main/version.txt
